spring.profiles.active=dev

# Allow large payloads for Base64 images
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB