# Production Profile: PostgreSQL Database on AWS
# These rely on Environment Variables set on the server
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shivani}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:pravin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.address=0.0.0.0
